Controllers/UserManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;
using TaskManager.Data;
using TaskManager.Models;
using TaskManager.ViewModels;

namespace TaskManager.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserManagementController : Controller
    {
        private readonly ApplicationDbContext _context;
        

        public UserManagementController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            var users = _context.Users.ToList();

            var viewModel = users.Select(u => new RegisterViewModel
            {
                FullName = u.FullName,
                Email = u.Email,
            }).ToList();

            return View(viewModel);
        }
    }
}

Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Account.css" />
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManager.styles.css" asp-append-version="true" />
</head>
<body>

    <nav class="sidebar bg-light border-end vh-100 position-fixed">
            <div class="sidebar-header text-center p-5">
                <h4 class="fw-bold text-primary">Finsbury Heinz</h4>
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <div class="small text-muted">
                        <img src="~/images/person-circle-outline.svg">
                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                            <span>@User.Identity?.Name</span>
                        }
                        else
                        {
                            <span>Guest</span>
                        }

                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a>
                            </li>
                            
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="UserManagement" asp-action="Index">User Management</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Task" asp-action="Create">Create Task</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Task" asp-action="Index">All Tasks</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Task" asp-action="EmployeeReport">Employee Report</a>
                                </li>
                            }
                            @if (User.IsInRole("User"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Task" asp-action="MyTasks">My Task</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Task" asp-action="EmployeeOverview">Overview</a>
                                </li>
                            }
                            <partial name="_LoginPartial" />
                        </ul>
                    </div>
                    
                </div>
            </div>
    </nav>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TaskManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>